Import Liabraries

In [9]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine,correlation

In [10]:
books = pd.read_excel("C://Users//HP//Desktop//RS.xlsx")
books

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [11]:
books_2 = books.iloc[:,1:]
books_2

User.ID                                         Book.Title  Book.Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [12]:
books_2.sort_values(['User.ID'])

User.ID                                         Book.Title  Book.Rating
2401        8                                              Wings            5
2400        8  The Western way: A practical guide to the West...            5
2399        8                            Ancient Celtic Romances            5
2402        8                                           Truckers            5
2405        8                                  The Art Of Celtia            7
...       ...                                                ...          ...
2395   278854      La crÃ³nica del PerÃº (CrÃ³nicas de AmÃ©rica)            7
2398   278854  Celtic Mythology (Library of the World's Myths...            8
2393   278854                         A corrente de Trewis Scott            7
2394   278854                                      As valkÃ­rias            7
2397   278854     A Treasury of Irish Myth, Legend, and Folklore            6

[10000 rows x 3 columns]

number of unique users in the dataset

In [13]:
len(books_2['User.ID'].unique())

2182

number of unique books in the dataset

In [14]:
len(books_2['Book.Title'].unique())

9659

In [15]:
books_3 = books_2.pivot_table(index='User.ID',
                                 columns='Book.Title',
                                 values='Book.Rating').reset_index(drop=True)

C:\Users\HP\anaconda3\lib\site-packages\pandas\core\apply.py:507: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  return self._try_aggregate_string_function(obj, f, *self.args, **self.kwargs)


TypeError: '<' not supported between instances of 'datetime.datetime' and 'int'

In [ ]:
books_3

Replacing the index values by unique user Ids

In [ ]:
books_3.index = books_2['User.ID'].unique()
books_3

Impute those NaNs with 0 values

In [ ]:
books_3.fillna(0,inplace=True)
books_3

Calculating Cosine Similarity between Users on array data

In [ ]:
user_sim = 1-pairwise_distances(books_3.values,metric='cosine')
user_sim

Store the results in a dataframe format

In [ ]:
user_sim2=pd.DataFrame(user_sim)
user_sim2

Set the index and column names to user ids 

In [ ]:
user_sim2.index=books_2['User.ID'].unique()
user_sim2.columns=books_2['User.ID'].unique()
user_sim2

Nullifying diagonal values

In [ ]:
np.fill_diagonal(user_sim,0)
user_sim2

Most Similar Users

In [ ]:
user_sim2.idxmax(axis=1)

extract the books which userId 162107 & 276726 have watched

In [ ]:
books_2[(books_2['User.ID']==162107) | (books_2['User.ID']==276726)]

extract the books which userId 276729 & 276726 have watched

In [ ]:
books_2[(books_2['User.ID']==276729) | (books_2['User.ID']==276726)]

In [ ]:
user_1=books_2[(books_2['User.ID']==276729)]
user_2=books_2[(books_2['User.ID']==276726)]

In [ ]:
user_1['Book.Title']

In [ ]:
user_2['Book.Title']

In [ ]:
pd.merge(user_1,user_2,on='Book.Title',how='outer')